pipeline {
    agent any

    environment {
        DB_URL = 'jdbc:postgresql://192.168.0.102:5433/employe_db'
        DB_USERNAME = 'springuser'
        DB_PASSWORD = 'springpass'
    }

    stages {

        stage('🔁 Pull Code') {
            steps {
                echo '🧲 Clonage du dépôt depuis GitHub...'
                checkout scm
            }
        }

        stage('🧱 Build Maven') {
            steps {
                echo '🔧 Compilation du projet Spring Boot...'
                sh './mvnw clean install'
            }
        }

        stage('📦 Liquibase Migration') {
            steps {
                echo '📥 Exécution des migrations Liquibase...'
                sh '''
                ./mvnw liquibase:update \
                  -Dliquibase.changeLogFile=src/main/resources/db.changelogs/db.changelog-master.yaml \
                  -Dliquibase.url=${DB_URL} \
                  -Dliquibase.username=${DB_USERNAME} \
                  -Dliquibase.password=${DB_PASSWORD}
                '''
            }
        }

        stage('🚀 Run Application') {
            steps {
                echo '🟢 Lancement de l\'application Spring Boot...'
                sh 'nohup ./mvnw spring-boot:run &'
            }
        }
    }

    post {
        success {
            echo '✅ Déploiement terminé avec succès !'
        }
        failure {
            echo '❌ Une erreur est survenue pendant le pipeline.'
        }
    }
}
